FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Define environment variables
ENV PYTHONUNBUFFERED=1

# Run the scraper bot
CMD ["python", "/app/scraping/bot.py"]