# Generated by Django 5.0.7 on 2024-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedimage',
            name='filename',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedimage',
            name='task_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapedimage',
            name='search_term',
            field=models.CharField(max_length=255),
        ),
    ]
